Updated with slf4j 1.6.4, logback 1.0.1, and not using the mumbo jumbo apacheds-all.
Still "works" with the exact same error as before:

03:21:51.461 [org.apache.directory.seserver.EmbeddedADSVer157.main()]
DEBUG o.a.d.s.l.s.l.e.i.DefaultSchemaLdifExtractor - BASE_PATH set to ,
outputDirectory set to /tmp/server-work
03:21:51.463 [org.apache.directory.seserver.EmbeddedADSVer157.main()]
DEBUG o.a.d.s.l.s.l.e.i.DefaultSchemaLdifExtractor - Output directory
exists: no need to create.
03:21:51.463 [org.apache.directory.seserver.EmbeddedADSVer157.main()]
INFO  o.a.d.s.l.s.l.e.i.DefaultSchemaLdifExtractor - Schema directory
'/tmp/server-work/schema' does exist: extracted state set to true.
03:21:51.472 [org.apache.directory.seserver.EmbeddedADSVer157.main()]
ERROR o.a.d.s.l.s.l.ldif.LdifSchemaLoader - ERR_10004 Expecting to find
a schema.ldif file in provided baseDirectory path
'/tmp/server-work/schema/ou=schema.ldif' but no such file found.
java.io.FileNotFoundException: ERR_10004 Expecting to find a schema.ldif
file in provided baseDirectory path
'/tmp/server-work/schema/ou=schema.ldif' but no such file found.
        at
org.apache.directory.shared.ldap.schema.loader.ldif.LdifSchemaLoader.<init>(LdifSchemaLoader.java:113)
        at
org.apache.directory.seserver.EmbeddedADSVer157.initSchemaPartition(EmbeddedADSVer157.java:127)
        at
org.apache.directory.seserver.EmbeddedADSVer157.initDirectoryService(EmbeddedADSVer157.java:161)
        at
org.apache.directory.seserver.EmbeddedADSVer157.<init>(EmbeddedADSVer157.java:233)
        at
org.apache.directory.seserver.EmbeddedADSVer157.main(EmbeddedADSVer157.java:266)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at
org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:679)